Генокрады с Поляриса (by deadphilosof)
animusdev/BlueTorchAdmiralty pull request #22
Opened 2017-12-20 14:36 UTC by AshtonFox

2017-12-20 14:39 UTC, ZerlGray commented
Точнее их абилки*

2017-12-20 19:00 UTC, TermService requested changes

2017-12-20 19:00 UTC, TermService commented on code/game/gamemodes/changeling/modularchangling.dm
> +//////////////////////////////////////////////////////
Что с символами?

2017-12-20 19:49 UTC, AshtonFox commented on code/game/gamemodes/changeling/modularchangling.dm
> +//////////////////////////////////////////////////////
Философ вносил комментарии к коду на кириллице(чего лучше не делать), кодировка проебалась при правке файла или при заливке на гитхаб

2017-12-20 19:53 UTC, ZerlGray commented on code/game/gamemodes/changeling/modularchangling.dm
> +//////////////////////////////////////////////////////
Мне просто так было удобнее в тонне англ. текста находить свои косяки на русском. Не баг а фича.

2017-12-20 20:15 UTC, TheReduce commented on code/game/gamemodes/changeling/modularchangling.dm
> +//////////////////////////////////////////////////////
Больше похоже на то, что ты скопипастил чей-то коммент, ибо, вроде, при коммите должны быть другие символы. А именно 
![image](https://user-images.githubusercontent.com/22078308/34226718-a2c69d1c-e5db-11e7-90bb-52bddbe0a8f6.png)

2017-12-20 20:16 UTC, TheReduce commented on code/game/gamemodes/changeling/modularchangling.dm
> +//////////////////////////////////////////////////////
В случае на скрине твои данные перенесутся на гит и затем буду нормально видны в Дрим Мейкере, а ты просто захламляешь репозиторий.

2017-12-21 00:16 UTC, AshtonFox commented on code/game/gamemodes/changeling/modularchangling.dm
> +//////////////////////////////////////////////////////
Бля, ну не знаю, может оно так при редактировании через Atom проёбывается. И я это заметил ещё во время редактирования, но что-то делать было лень. Извините, что мы с философом обосрали .dm-ки и репу комментариями на русском без кодировки. Прос ти те

2017-12-21 04:40 UTC, ZerlGray commented on code/game/gamemodes/changeling/modularchangling.dm
> +//////////////////////////////////////////////////////
Э.... Щас бы комменты копипастить без кода, просто чтобы сбить кодировку.

2017-12-21 08:28 UTC, TermService commented on code/game/gamemodes/changeling/modularchangling.dm
> +//////////////////////////////////////////////////////
Переведите на англ, а чтобы не потерять впишите свой ник

2017-12-21 08:51 UTC, TermService requested changes

2017-12-21 08:51 UTC, TermService commented on code/game/gamemodes/changeling/modularchangling.dm
> +	src << "<span class='notice'>We empower ourselves. Our abilities will now be extra potent.</span>"
Перепишите через to_chat(). Это относится ко всему коммиту

2017-12-21 15:50 UTC, ZerlGray commented on code/game/gamemodes/changeling/modularchangling.dm
> +	src << "<span class='notice'>We empower ourselves. Our abilities will now be extra potent.</span>"
Почему бы не смержить и не дать это сделать следующим пуллом?
У меня то доступа нет. 
А to_chat или нет, это лишь вопрос унификации кода же под один тип.

2017-12-22 10:35 UTC, merged